### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by chicofranchico** [sampointer/fluent-plugin-cloudwatch-ingest#13]
Hi, the following api calls gets a rate limit exceeded throttling from AWS if you have too many log streams:

https://github.com/sampointer/fluent-plugin-cloudwatch-ingest/blob/b4a25092debbf7fec80c3c37defdc1e7cdd8beb3/lib/fluent/plugin/in_cloudwatch_ingest.rb#L198
https://github.com/sampointer/fluent-plugin-cloudwatch-ingest/blob/b4a25092debbf7fec80c3c37defdc1e7cdd8beb3/lib/fluent/plugin/in_cloudwatch_ingest.rb#L204

The throttling happens on "describe logs" and this limitation is hard capped (not possible to increase the number of calls per second towards that endpoint).

I made a pull request with some changes and I'm very open to criticism and or side effects I may have overlooked while doing it. I never did any real Ruby coding so more help is also appreciated.
#12

**Comment by sampointer** [comment]
Hey. Apologies for the delay in replying. I'll take a look at the PR in short order!

**Comment by sampointer** [comment]
Merged https://github.com/sampointer/fluent-plugin-cloudwatch-ingest/pull/12. Published as `1.5.0.rc1`. See http://guides.rubygems.org/patterns/#prerelease-gems for information on installing pre-release gems.

Help from any party fixing the lint errors would speed up the release of `1.5.0` proper: https://circleci.com/gh/sampointer/fluent-plugin-cloudwatch-ingest
