### ISSUE TITLE
[Question] Use this plugin with the fluent/fluentd-kubernetes-daemonset images

### ISSUE THREAD

**Issue by alterx** [sampointer/fluent-plugin-cloudwatch-ingest#8]
Do you think there's a way to use this plugin with the fluent-kubernetes-daemonset images instead of the one provided by default (https://github.com/ryotarai/fluent-plugin-cloudwatch-logs).

I'm having issues integrating it with CloudWatch and it seems like the author isn't worried about addressing an issue that makes it unusable (it least for me and a couple of people that have reported the issue).

I want to build a new image but I have no idea of how well will your plugin integrate with fluent-kubernetes-daemonset. Have you tried this or are you just using another image altogether?

Thanks in advance

**Comment by sampointer** [comment]
I'm not using any container image in my main deployment of this plugin. Those images, looking at the tags, are built using fluentd v0.12.x. I've not tested this plugin under that version, so if you're interested in making a new set of images that is probably the place to start. Or the converse: update the images to v0.14.x

I found the upgrade to 0.14.x extremely painful, being honest, and ended up submitting a number of upstream fixes to both fluentd-proper and the various elasticsearch drivers to get it all [working](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Asampointer+is%3Apublic+).

For me 0.14.x - or at least subsecond timestamps - was an absolute must that I couldn't believe wasn't a feature of fluentd from the start.

I feel your pain with the original plugin. It is what prompted me to make this new version despite having contributed the iam work and various other fixes, with varying success of PR activity.
